---
all:
  children:
    app:
      hosts:
        app-server:
          ansible_host: "{{ app_server_ip }}"
          ansible_user: root  # Explicitly set the user
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"  # Explicitly set the key
    monitoring:
      hosts:
        monitoring-server:
          ansible_host: "{{ monitoring_server_ip }}"
          ansible_user: root  # Explicitly set the user
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"  # Explicitly set the key